Validation feature
david-lafontant/Portfolio pull request #22
Opened 2021-12-16 12:44 UTC by david-lafontant

Create a validation feature

2021-12-16 16:12 UTC, elyor-doniyorov requested changes
Hi @david-lafontant, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost-there](https://user-images.githubusercontent.com/67087664/146405503-b4b77755-7fb7-4aa3-9fe6-11b4e99786fd.gif)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-16 16:12 UTC, elyor-doniyorov commented on script/validation.js
> +function validateEmail(input, requiredMsg, invalidMsg) {
- [ ] Make sure if a user submits the contact form with the email field containing `uppercase `characters an error message should show up. Kindly, fix it!

2021-12-16 21:46 UTC, david-lafontant commented on index.html
> +            <input type="text" name="name" class="input-field text-input" placeholder="Please enter your name" id="name" maxlength="30"/>
Thank you for your comment. I implemented a solution for this issue.
[ solution on index.html](https://github.com/david-lafontant/Portfolio/blob/4f83af3ced89e4443414590177158f0b053600bf/index.html#L305)
[solution on the script](https://github.com/david-lafontant/Portfolio/blob/4f83af3ced89e4443414590177158f0b053600bf/script/validation.js#L68)

2021-12-16 22:00 UTC, david-lafontant commented on script/validation.js
> +function validateEmail(input, requiredMsg, invalidMsg) {
Thank you very much for your comment. I implemented a solution with regular expression in the validateEmail function in the script file. I hope this meets your expectations:
Link to the solution: [click here](https://github.com/david-lafontant/Portfolio/blob/4f83af3ced89e4443414590177158f0b053600bf/script/validation.js#L42)
![validation-error-uppercase](https://user-images.githubusercontent.com/39683557/146454926-f38fa87f-dddb-42ed-bfd0-def772dcd429.png)

2021-12-16 22:50 UTC, andersonlebon requested changes
### Hi @david-lafontant 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Suggested changes
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2021-12-16 22:50 UTC, andersonlebon commented on script/validation.js
> +  });
- [ ] As the previous review said. The user should be prevented from submitting the form with an email input containing an uppercase letter and a message should be displayed near the submit button. Let's go and implement this feature :muscle: :muscle: :muscle:

2021-12-20 20:30 UTC, alonsofl approved these changes
Hi @david-lafontant,

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![](https://media1.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-23 15:10 UTC, merged