Popup feature
david-lafontant/Portfolio pull request #25
Opened 2021-12-18 16:13 UTC by david-lafontant

implement the following:

- [ ] When the user clicks (or taps) the button to check project details, the popup with details about the project appears.
- [ ] When the user clicks (or taps) the close (X) button, the popup disappears.
- [ ] implement popups for both mobile and desktop screen sizes
- [ ] stick to the design as much as possible
- [ ] associate each project with the popup window details

2021-12-18 18:13 UTC, alonsofl requested changes
Hi @david-lafontant and @eduardosancho,

You have done a great job so far! :muscle:
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media2.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif)

## Required Changes ♻️
_Check the comments under the review._

## To highlight :dart:
- Linters are working correctly :heavy_check_mark:

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-18 18:13 UTC, alonsofl commented on script/popup.js
> +/* eslint-disable no-magic-numbers */
- [ ] There is an issue with your popup window because it is supposed to appear above the current content, but you are actually replacing the whole `<body>` content, and when closing going back to the homepage. Please, kindly fix this issue in order to make it work as a "popup window" :smiley: :pushpin:
![image](https://user-images.githubusercontent.com/81522435/146651311-7327c1aa-93f4-4b2a-a9c8-729dad7f1598.png)

- [ ] Also, I would suggest updating the (X) icon for the mobile version because it's appearing to the left side and according to the Figma design it should be to the right side. Please, fix this issue in order to match the design requirements :raised_hands: 

| Your design | Figma design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/81522435/146651405-91ef00c2-1778-4bb5-b723-b59bf9beec05.png) | ![image](https://user-images.githubusercontent.com/81522435/146651416-22b0e993-1604-4ff5-b84e-99085e1ba7fd.png) |

2021-12-18 18:13 UTC, alonsofl commented on index.html
>              <li class="canopy-detail">
- [ ] According to the project requirements you should store the project's information with a JavaScript object containing the "project information" and generate this section dynamically. Please, update this in order to match the project requirements :pushpin: :pray:
![image](https://user-images.githubusercontent.com/81522435/146651544-4647abd8-257b-4481-bd9c-4911163b7074.png)

2021-12-18 22:05 UTC, david-lafontant commented on index.html
>              <li class="canopy-detail">
Thank you for your work. However, since the beginning, the popup is created entirely in the popup.js file. The similarities come from the fact that I reuse in the popup the structure of the index.html and also most of the style, in order to be more efficient. Thank your comment I remove the substring that is probably the cause of this ambiguity and replace it with a variable. Hope this will satisfy your expectations.

2021-12-18 22:06 UTC, david-lafontant commented on script/popup.js
> +/* eslint-disable no-magic-numbers */
I want to thank you for the time devoted to reviewing my project. I just want to point to you about the optional suggestion about the popup window, what I did was neither allowed nor prohibited.

[ Portfolio: details popup window](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/8_popup.md)

2021-12-18 22:06 UTC, david-lafontant commented on script/popup.js
> +/* eslint-disable no-magic-numbers */
Thank you for your comment about the location of the close button. I solved it.

2021-12-18 22:51 UTC, alonsofl requested changes
Hi @david-lafontant,

Great work on making the changes requested 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://media2.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-18 22:51 UTC, alonsofl commented on script/popup.js
> +/* eslint-disable no-magic-numbers */
- [ ] As it was requested before, the "popup window" should appear on top of the content and not replace the entire `<body>` content. As you can see in the Figma design when you open the popup window, you can see the content behind (blurred) and in your portfolio, the popup content replaces all the `<body>` so there is no actual content behind. Please, kindly update your portfolio in order to make the window popup function as it is required :raised_hands:
![image](https://user-images.githubusercontent.com/81522435/146657297-7c76de22-9de1-43a4-bbfb-70de7c36fe4c.png)

- [ ] About the projects section, it is a requirement to generate it dynamically and you can achieve this by creating an array in JavaScript and each item could be an object containing all the information required (name, description, featured image, technologies, link to live version, link to source) for each project, with this information you could loop through this array and generate the projects section. Please, kindly update your project in order to generate the projects section dynamically and you can get that information to generate also the popup :wink:
![image](https://user-images.githubusercontent.com/81522435/146657514-b191253f-5ad3-495f-8d83-d5150d23ba0c.png)

2021-12-19 00:12 UTC, david-lafontant commented on script/popup.js
> +/* eslint-disable no-magic-numbers */
I did it. I dit it in popup.js. everything in the popup is created dynamically. Everything.

2021-12-19 01:00 UTC, alonsofl commented on script/popup.js
> +/* eslint-disable no-magic-numbers */
Hello, @david-lafontant!
I hope you're doing well. For this milestone, you were supposed to remove all the project content from the index.html and replace it dynamically with the information from JavaScript (you could see my recommendation above). Why is it a requirement to do it this way? Because most of the time you will be working with information coming from somewhere else (not your HTML code) for example, an API. And you will have to use that information to create ALL the application content (in your case the HTML) dynamically. For this reason, is that you haven't met this requirement because you are still using your HTML code (even when the requirement explicitly says that you have to dynamically create everything). And in the file that you mention I can only see a little information when it should contain all the information related to the projects (as the requirements mention: name, description, featured, image, technologies, links).

![image](https://user-images.githubusercontent.com/81522435/146659527-803816c2-6cab-469d-aea2-94ed6c6a5a85.png)

I will try to be clear enough with a project that I worked on a few days ago. In the next image, you will see a common API response (in this case, a restaurants list), notice that each restaurant is an object (with all the required information), and all the objects are inside an array so you can manipulate the information.

![image](https://user-images.githubusercontent.com/81522435/146659678-18bbec5a-1fcf-4946-87a7-9b6659f60b12.png)

I hope this explanation it's clear enough :raised_hands:

2021-12-20 15:27 UTC, david-lafontant commented on script/popup.js
> +/* eslint-disable no-magic-numbers */
So, you want me to hard code them instead of extracting them dynamically.  So if I have fifty projects, I have to hardcode fifty objects. 
instead of `"tile: Tonic" ` I  did this:

- I extract all the titles with:  `const myHeadings = document.getElementsByClassName('cardH2');` (line 6 of the popup.js file)  

- Then I create an array that will contain the value of each heading: `const headingContent = []; ` (line 8).

-  Then I use a loop to retrieve the content (the value) of the headings and put them in the array created:

`for (let num = 0; num < myHeadings.length; num += 1){

  const item = `<h2 class="cardH2 cardH2modal" id="
  h2Modal">${myHeadings[num].textContent}</h2>
  headingContent.push(item);
}` `; (line 82 to 89).

- After I add them to the array of objects created at line 12 : `const popup = [];` : 

for (let num = 0; num < myCanopy.length; num += 1){
  const item = {
    "lieLink": lives,
    "sourceLink": sources,
"theCanopy": canopy[num],
**"theHead": headingContent[num],**
"theImage": imageContent[num]
  };`


- Then the key: value pair of each object of the array is added to the template: 

`  ${popup[num].theHead}` line 98

**I did this for EACH element.**

- and finally, **the popup is created when the user clicks on one of the project buttons**.

If it is a requirement to hard code 100 objects I can do it. However, all the benefits of dynamic HTML will vanish.

2021-12-21 18:01 UTC, closed without merging