Popup feature
david-lafontant/Portfolio pull request #28
Opened 2021-12-21 18:26 UTC by david-lafontant

# Popup Feature
### Implement the following interactions:

- [ ] When the user clicks (or taps) the button to check project details, the popup with details about the project appears.
- [ ] When the user clicks (or taps) the close (X) button, the popup disappears.
- [ ] popups for both mobile and desktop screen sizes:
- [ ] stick to the design as much as possible (e.g., font, colors, images, tests, margins) using the templates in Figma.
- [ ] use a JavaScript array to store all of the information for all projects.
- [ ] store the following pieces of data in a JavaScript object, at a minimum: name, description, featured image, technologies, link to live version, link to source.
- [ ] update the main page so that the projects section is created dynamically using the information stored in that JavaScript object. 
- [ ] use pair-programming for this project.

2021-12-21 19:07 UTC, alonsofl requested changes
Hi @david-lafontant,

You have done a great job so far! :muscle:
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media2.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif)

## Required Changes ♻️
_Check the comments under the review._

## To highlight :dart:
- The popup window is working as expected :heavy_check_mark:

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-21 19:07 UTC, alonsofl commented on script/popup.js
> +const projectBtn = document.querySelectorAll('.myButton');
- [ ] There is an issue with the projects section in your portfolio because one of the requirements is to create the section dynamically using JavaScript, and this means storing all the information in a variable. Remember that for each project you need to store at least the following information: name, description, featured image, technologies, link to live version, link to the source. Also, keep in mind that you have to associate each project with the window popup details :wink: :pushpin:
![image](https://user-images.githubusercontent.com/81522435/146984418-b7622294-03e0-44bb-a84c-abac4c99ce07.png)

2021-12-21 19:21 UTC, david-lafontant commented on script/popup.js
> +const projectBtn = document.querySelectorAll('.myButton');
Yo repeatedly said that the popup is not created dynamically. Please show me where I create the popup inside the index.html file?

2021-12-21 19:35 UTC, alonsofl commented on script/popup.js
> +const projectBtn = document.querySelectorAll('.myButton');
Actually, yes. You could check all the information about this requirement in the [original PR](https://github.com/david-lafontant/Portfolio/pull/25).

Also, I didn't say that the popup is not created dynamically, I say that the projects section should be created dynamically because it is a requirement.
![image](https://user-images.githubusercontent.com/81522435/146987012-d2d6ceb8-dba4-4ae9-bf4b-bd6ce5efa881.png)

And answering your question and clarifying the requirement, here is where the section it's not created dynamically (all the projects section).
![image](https://user-images.githubusercontent.com/81522435/146986466-920b530a-a452-44d9-a295-c2d933c295cc.png)
**Hint: The projects section should only contain a `<section>` tag instead of all the HTML related to the projects. And this `<section>` tag will help to create all the content inside/below DYNAMICALLY**

Please, if this information is not clear just let me know :wink:

2021-12-21 20:07 UTC, alonsofl commented on script/popup.js
> +const projectBtn = document.querySelectorAll('.myButton');
@david-lafontant you could check all the information about this requirement in the [original PR](https://github.com/david-lafontant/Portfolio/pull/25).

Also, I didn't say that the "popup" is not created dynamically, I say that the "projects" section should be created dynamically because it is a requirement.
![image](https://user-images.githubusercontent.com/81522435/146987012-d2d6ceb8-dba4-4ae9-bf4b-bd6ce5efa881.png)

And answering your question and clarifying the requirement, here is where the section it's not created dynamically (all the projects section).
![image](https://user-images.githubusercontent.com/81522435/146986466-920b530a-a452-44d9-a295-c2d933c295cc.png)
**Hint: The projects section should contain a tag instead of all the HTML related to the projects. And this tag will help to create all the content inside/below DYNAMICALLY**

Please, if this information is not clear just let me know :wink:

2021-12-21 20:54 UTC, david-lafontant commented on script/popup.js
> +const projectBtn = document.querySelectorAll('.myButton');
@alonsofl for the project I proceed the following way:
The project section actually is a tag. is a `div `created dynamically in line 136 of the popup.js. After creating it, I gave it the id of overlay (line 138),  is filled with its content in line 139(all the HTML you saw),  and appended to the body element in line 140.  

a) Create variables that hold the information that I will need to add properties to the object that will be part of the array of objects named popup ( line 1 to 64 of the file popup.js);
b) create an empty array named popup (line 66 of popup.js);
c) Fill the popup array with objects created with properties that come from the variables created from line 1 to line 64;
d) create a function named popupTemplate that will generate the popup from the properties of the related object. Its argument is the index of the "See project" button clicked. 
e) from line 118 to line 141 of popup.js, the procedures to launch the popup and remove it are implemented. the popup is created from line 136 to line 140 and destroyed with the call of the closePopup();.

2021-12-21 22:54 UTC, david-lafontant commented on script/popup.js
> +const projectBtn = document.querySelectorAll('.myButton');
@alonsofl If I understand I can let the popup.js like it is, however the 4 projects created before ( If I am wrong in the second block of the first module) have to be created also dynamically when the page is loading, isn't it?

2021-12-22 01:57 UTC, alonsofl commented on script/popup.js
> +const projectBtn = document.querySelectorAll('.myButton');
@david-lafontant basically, the first thing is to remove the hardcoded projects from the HTML and store the information in JS. For this, you could create an array and each element could be an object containing project information (remember that the requirement says to store at least: name, description, featured image, technologies, link to live version, link to the source):
```
const projects = [{
    name: "Tonic",
    description: "Project description.",
    image: "path_to_img.jpg",
    technologies: ["HTML", "CSS", "JS"],
    link: "link_to_demo",
},
{
    name: "Tonic 2",
    description: "Project 2 description.",
    image: "path_to_img.jpg",
    technologies: ["HTML", "CSS", "JS"],
    link: "link_to_demo",
}]

```
With this structure, you could loop through the project's array and create each card dynamically, you will have to [create the elements](https://www.w3schools.com/Jsref/met_document_createelement.asp) or you could use a [method to insert HTML](https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentHTML) and use your HTML code. Remember that you don't have to change the styling because you can add a `className` for each element and use the same style ([you could see this](https://www.w3schools.com/jsref/prop_html_classname.asp)).

After creating the cards/projects section dynamically, when clicking the popup it should retrieve the information of the clicked project, e.g., you could use an ID as a parameter so you can identify the project.

I hope this information is clear enough about the project requirement :wink:

2021-12-22 14:44 UTC, david-lafontant commented on script/popup.js
> +const projectBtn = document.querySelectorAll('.myButton');
Thank you @alonsofl for your time and your guidance.

2021-12-24 02:05 UTC, mmsesay approved these changes
Hi @david-lafontant , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-24 09:46 UTC, merged